name: example-command
on:
  repository_dispatch:
    types: [my-event]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: actions/checkout@v2
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
