name: example-command
on:
  repository_dispatch:
    types: [my-event]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: actions/checkout@v2
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload.pubinfo) }}
      - run: mkdir -p dene
      - run: echo "$PAYLOAD_CONTEXT" > dene/info.json
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: dene
      - name: Commit files
        run: |
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add json file" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: master
