name: example-command
on:
  repository_dispatch:
    types: [my-event]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: actions/checkout@v2
      - run: mkdir -p dene
      - run: echo ${{ github.event.client_payload.pubinfo }} > dene/info.json
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: dene
