name: NeuroLibre - Add publication to the website 
on:
  repository_dispatch:
    types: [publish]
env:
  PUB_NAME: ${{ toJson(github.event.client_payload.pub_name) }}
  PUB_INFO: ${{ toJson(github.event.client_payload.pub_info) }}
  PUB_LABEL: ${{ toJson(github.event.client_payload.pub_info.labels[0]) }}
  PUB_TAG: ${{ github.event.client_payload.pub_tag }}
jobs:
  updateWebsite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout neurolibre/neurolibre.com
        uses: actions/checkout@v2
      - name: Dump the JSON received from dispatch 
        run: |
          mkdir -p data/nlbooks
          echo "$PUB_INFO" > data/nlbooks/$PUB_NAME.json
          echo ::set-env name=PUB_AUTHOR::$(if [ -z "${{ github.event.client_payload.pub_info.authors[1].name }}" ]; then echo ${{ github.event.client_payload.pub_info.authors[0].name }}; else echo ${{ github.event.client_payload.pub_info.authors[0].name }} et al.; fi)
          echo ::set-env name=TAG_TYPE::$(echo $PUB_TAG | awk -F"-" '{print $1}')
          echo ::set-env name=TAG_VER::$(echo $PUB_TAG | awk -F"-" '{print $2}')
      - name: Conditionally assign ENV vars
        run: |          
          if [[ ${{ env.TAG_TYPE }} == "pub" ]] && [[ ${{ env.TAG_VER }} == "v1" ]]; then
            echo "First version."
            echo ::set-env name=PR_TITLE::$(echo "✨${{ env.PUB_NAME }} by  ${{ env.PUB_AUTHOR }}")
            echo ::set-env name=PR_LABELS::$(echo "new, ${{ env.PUB_LABEL }}")
          elif [[ ${{ env.TAG_TYPE }} == "pub" ]] && [[ ${{ env.TAG_VER }} != "v1" ]]; then
            echo "New version."
            echo ::set-env name=PR_TITLE::$(echo "🚀${{ env.PUB_NAME }} (${{ env.TAG_VER }}) by  ${{ env.PUB_AUTHOR }}")
            echo ::set-env name=PR_LABELS::$(echo "update, ${{ env.PUB_LABEL }}")
          else
            echo "This is NOT type publish. Ensure that workflow logic is in harmony with trigger tags."
          fi          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.PAT }}
          commit-message: '[ADD] ${{ env.PUB_NAME }}.json'
          committer: NeuroLibre <neurolibre@gmail.com>
          author: NeuroLibre < NeuroLibre@users.noreply.github.com>
          title: '${{ env.PR_TITLE }}'
          body: |
            ## Title
            
            ${{ toJson(github.event.client_payload.pub_info.title) }}
            
            ## Origin 
            
            This pull request has been automatially created from [${{ env.PUB_NAME }}](https://github.com/neurolibre/${{ env.PUB_NAME }}) repository.
            
            ## Checklist
            
            - [ ] Publication is properly versioned (`pub-v#`). [See all releases](https://github.com/neurolibre/${{ env.PUB_NAME }}/releases).
            - [ ] [Link to the publication](https://neurolibre.com) is not broken.
            - [ ] [Publication metadata](https://github.com/neurolibre/neurolibre.com/blob/master/data/nlbooks/${{ env.PUB_NAME }}.json) is properly fetched.
            - [ ] Badges are properly populated on the publication card and the links are not broken. 
            - [ ] Featured image is visible on the publication card. 

          labels: '${{ env.PR_LABELS }}'
          assignees: agahkarakuzu
          reviewers: agahkarakuzu
          branch: '${{ env.PUB_NAME }}'
