name: NeuroLibre - Add publication to the website 
on:
  repository_dispatch:
    types: [publish]
env:
  PUB_NAME: ${{ github.event.repository.name }}
  PUB_INFO: ${{ toJson(github.event.client_payload.pubinfo) }}
  PUB_TAG: ${{ github.event.client_payload.pub_tag }}
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout neurolibre/neurolibre.com
        uses: actions/checkout@v2
      - name: Dump the JSON received from dispatch 
        run: |
          mkdir -p data/nlbooks
          echo "$PUB_INFO" > data/nlbooks/$PUB_NAME.json
          echo ::set-env name=PUB_AUTHOR::$(if [ -z "${{ github.event.client_payload.pubinfo.authors[1].name }}" ]; then echo ${{ github.event.client_payload.pubinfo.authors[0].name }}; else echo ${{ github.event.client_payload.pubinfo.authors[0].name }}; fi)
          echo ::set-env name=TAG_TYPE::$(echo $PUB_TAG | awk -F"-" '{print $1}')
          echo ::set-env name=TAG_VER::$(echo $PUB_TAG | awk -F"-" '{print $2}')
      - name: Conditionally assign ENV vars
        run: |          
          echo "Bu ${{ env.TAG_TYPE }}"
          echo ${{ env.TAG_VER }}
          if [[ ${{ env.TAG_TYPE }} == "pub" ]] && [[ ${{ env.TAG_VER }} == "v1" ]]; then
            echo "Published for the first time."
            echo ::set-env name=PR_TITLE::$(echo "✨New publication ✨ ${{ env.PUB_NAME }} by  ${{ env.PUB_AUTHOR }}")

          elif [[ ${{ env.TAG_TYPE }} == "pub" ]] && [[ ${{ env.TAG_VER }} != "v1" ]]; then
            echo "Updated publication."
            echo ::set-env name=PR_TITLE::$(echo "✨UPDATE ✨ ${{ env.PUB_NAME }} by  ${{ env.PUB_AUTHOR }}")
          else
            echo "This is NOT type publish. Ensure that workflow logic is in harmony with trigger tags."
          fi          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.PAT }}
          commit-message: '[ADD] ${{ env.PUB_NAME }}.json'
          committer: NeuroLibre <neurolibre@gmail.com>
          author: NeuroLibre < NeuroLibre@users.noreply.github.com>
          title: '${{ env.PR_TITLE }}'
          body: |
            This pull request has been automatially generated
            - [ ] Do this
            - [ ] Do that
          labels: ready for publication
          assignees: agahkarakuzu
          reviewers: agahkarakuzu
          branch: '${{ env.PUB_NAME }}'
