name: NeuroLibre - Add publication to the website 
on:
  repository_dispatch:
    types: [my-event]
env:
  PUB_INFO: ${{ toJson(github.event.client_payload.pubinfo) }}
  PUB_NAME: ${{ github.event.repository.name }}
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout neurolibre/neurolibre.com
        uses: actions/checkout@v2
      - name: Dump the JSON received from dispatch 
        run: |
          mkdir -p data/nlbooks
          echo "$PUB_INFO" > data/nlbooks/$PUB_NAME.json
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.PAT }}
          commit-message: Add $PUB_NAME.json
          committer: NeuroLibre <neurolibre@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '🆕✨ ${{ env.PUB_NAME }}'
          body: |
            This pull request has been automatially generated
            - [ ] Do this
            - [ ] Do that
          labels: new_publication
          assignees: agahkarakuzu
          reviewers: agahkarakuzu
          branch: $PUB_NAME
